### ISSUE TITLE
Evergreen Add ring property to Test-AppList, because Type and Architecture are not always sufficient

### ISSUE THREAD

**Issue by rohgin** [MSEndpointMgr/IntuneAppFactory#11]
When Adding Teams from Evergreen 
using the following in appList.json
"FilterOptions": [
        {
            "Architecture": "x64",
            "Type": "msi"
        }
It will return multiple choices and the pipeline will fail.

In Test-AppList.ps1 you should add

 if ($FilterOptions.Ring) {
            $FilterList.Add("`$PSItem.Ring -eq ""$($FilterOptions.Ring)""") | Out-Null
        }

When you add the following to the appList.json, it will succesfully run through the pipeline and select the current version.
"FilterOptions": [
        {
            "Architecture": "x64",
            "Type": "msi",
            "Ring": "General"
        }

**Comment by NickolajA** [comment]
Thanks! I've added that now and it will be out with the next release, in addition to Edition and Language filter options.
