### ISSUE TITLE
Save-installer needs redirect for winget downloadlinks

### ISSUE THREAD

**Issue by DennisBergemann** [MSEndpointMgr/IntuneAppFactory#12]
Hi,
download for winget fetches wrong file when getting as example keepass from winget, because its sourceforge with redirect.

Solution:

Use -userAgent wget as param for invoke-webrequest

Best regards

**Comment by NickolajA** [comment]
Thanks, just validated that with e.g. KeePass and it works way better. I'll fix this.

**Comment by DennisBergemann** [comment]
Nice to see that i could support. I did it for mine in azure dev ops as well.

By the way. Much thanks again for this Factory Project.
